# Generated by Django 2.0.4 on 2018-04-20 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('phone', models.IntegerField()),
                ('register_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
