# Generated by Django 2.0.4 on 2018-04-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopingcart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=80)),
                ('BookId', models.CharField(max_length=100, unique=True)),
                ('BookName', models.CharField(max_length=200, unique=True)),
                ('Index', models.IntegerField()),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
